### ISSUE TITLE
Webhook notifications for first bloods on challenges

### ISSUE THREAD

**Issue by yusufsallam64** [BCACTF/arcs-issues#20]
Having web hook send out more notifications to Discord mid-ctf would be nice and would give it more of a purpose.

**Comment by Blckbrry-Pi** [comment]
Addressed by https://github.com/BCACTF/arcs-webhook/commit/41a155a7a83bd394951241ba32110534cd7a1a8d. Currently untested.

**Comment by Blckbrry-Pi** [comment]
Done and tested!
